name: NUS Hackers
domain: http://nushackers.org
description: >
  Linux, Open Source Software, and the Hacker Culture
markdown: redcarpet
redcarpet:
  extensions: [autolink]
highlighter: pygments
permalink: /:year/:month/:title
paginate: 10
paginate_path: /articles/page/:num
mainpages:
  - url: /about
    title: About
  - url: /discussion
    title: Discussion
  - url: /events
    title: Events
  - url: /code
    title: Code
  - url: /contact
    title: Contact
