baseURL = "https://www.nushackers.org/"
languageCode = "en-us"
title = "NUS Hackers"
copyright = "NUS Hackers"
buildFuture = true
disqusShortname = "nushackers"
enableEmoji = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "emacs"
ignoreFiles = ["\\.scss$"]
googleAnalytics = "UA-141681743-1"

[params]
  description = "NUS Hackers"

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
  name = "About"
  identifier = "About"
  weight = 1
  url = "/about"
[[menu.main]]
  name = "Discussion"
  identifier = "Discussion"
  weight = 2
  url = "/discussion"
[[menu.main]]
  name = "Events"
  identifier = "Events"
  weight = 3
  url = "/events"
[[menu.main]]
  name = "Code"
  identifier = "Code"
  weight = 4
  url = "/code"
[[menu.main]]
  name = "Contact"
  identifier = "Contact"
  weight = 5
  url = "/contact"
